name: Flatpak test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:flatpak/stable
        sudo add-apt-repository 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main' # Needed for updates to work
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev attr automake gettext autopoint bison  dbus gtk-doc-tools \
        libfuse-dev ostree libostree-dev libarchive-dev libzstd-dev libcap-dev libattr1-dev libdw-dev libelf-dev python3-pyparsing \
        libjson-glib-dev shared-mime-info desktop-file-utils libpolkit-agent-1-dev libpolkit-gobject-1-dev \
        libseccomp-dev libsoup2.4-dev libcurl4-openssl-dev libsystemd-dev libxml2-utils libgpgme11-dev gobject-introspection \
        libgirepository1.0-dev libappstream-dev libdconf-dev clang e2fslibs-dev
        sudo apt-get install libappstream-glib8
    - name: Check out flatpak
      run: git clone -b flatpak-1.12.x https://github.com/flatpak/flatpak/ --recurse-submodules
    - name: configure
      run: |
        cd flatpak
        ./autogen.sh
        ./configure
    - name: Build flatpak
      run: |
        make -j $(getconf _NPROCESSORS_ONLN)
        sudo make install
